# .github/workflows/md_to_pdf.yml

name: markdown to pdf
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      # - master
      - md_to_pdf
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'docs/**.md'
      - 'docs/images/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          images_dir: docs/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
          table_of_contents: true
          highlight_theme: styles/github_dark_dimmed.css
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs